extends:
  - '@redhat-cloud-services/eslint-config-redhat-cloud-services'
  - 'plugin:@typescript-eslint/recommended'

parser: '@typescript-eslint/parser'
globals:
  insights: 'readonly'
rules:
  react/prop-types: 'off'
