# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
apiVersion: v1
kind: Template
metadata:
  name: manifests
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: manifests
    spec:
      envName: ${ENV_NAME}
      feoConfigEnabled: true
      title: Manifests
      deploymentRepo: https://github.com/RedHatInsights/subscription-central-ui
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/manifests
      image: ${IMAGE}:${IMAGE_TAG}
      searchEntries:
        - id: 'manifests'
          title: Manifests
          href: /subscriptions/manifests
          description: Create, manage, and export subscription manifests for Red Hat Satellite.
      bundleSegments:
        - segmentId: manifests
          bundleId: subscriptions
          navItems:
            - id: manifests
              title: Manifests
              href: /subscriptions/manifests
          position: 150
      module:
        manifestLocation: '/apps/manifests/fed-mods.json'
        modules:
          - id: 'manifests'
            module: './RootApp'
            routes:
              - pathname: /subscriptions/manifests

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/subscription-central-ui
