apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/subscription-central-ui?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/v1.26.0/pipelines/docker-build.yaml
  creationTimestamp:
  labels:
    appstudio.openshift.io/application: subscription-central-ui
    appstudio.openshift.io/component: subscription-central-ui
    pipelines.appstudio.openshift.io/type: build
  name: subscription-central-ui-on-push
  namespace: teamnado-konflux-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/teamnado-konflux-tenant/subscription-central-ui/subscription-central-ui:{{revision}}
    - name: dockerfile
      value: ./build-tools/Dockerfile
  pipelineRef:
    name: docker-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-subscription-central-ui
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
